language: node_js
sudo: required
node_js:
- '6'
before_deploy: 
- curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.6.1/linux64 | tar -zx
- chmod -R u+x ./Bluemix_CLI/bin
- chmod +x ./deploy.sh
- ./Bluemix_CLI/bin/bluemix plugin install Cloud-Functions -r Bluemix
deploy: 
  provider: script
  script: ./deploy.sh
  on:
    repo: ibm-watson-data-lab/soingest
    branch: travis
  skip_cleanup: true
